/**
 * @file CitationKeyStore — sqlite-backed persistence of studio-minted citation keys
 * @description Web mode has no Better BibTeX to serve as source of truth for
 *              citation keys, so studio has to mint + remember them itself.
 *              This store is the *memory*: `itemKey → { citationKey, origin }`.
 *
 *              Origin classifies where the key came from — used by the
 *              orchestrator's 3-layer fallback resolution:
 *
 *                  1. `data.citationKey` on the fetched item     (BBT-synced)
 *                  2. store.get(itemKey)                          (this file)
 *                  3. mintCitationKey(item, store.getAllKeys())   (fresh mint)
 *
 *              and by UI panels that want to warn users "N keys generated by
 *              Studio, may drift when BBT comes online".
 *
 *              Schema is versioned via the MetaDb-style migrations array —
 *              same node:sqlite + WAL + STRICT-table pattern to keep migration
 *              surgery uniform across the codebase (MetaDb, this store, and
 *              any future stage-B artifact-cache DB).
 *
 * @see src/main/services/history/MetaDb.ts (schema-migration template)
 */

import { createRequire } from 'node:module';
import path from 'node:path';
import fs from 'node:fs';
import type { DatabaseSync } from 'node:sqlite';
import type { ZoteroCitationKeyOrigin } from '../../../../shared/types/zotero';
import { createLogger } from '../LoggerService';

const _require = createRequire(import.meta.url);
const sqliteModule = _require('node:sqlite') as typeof import('node:sqlite');
const DatabaseSyncCtor = sqliteModule.DatabaseSync;

const logger = createLogger('CitationKeyStore');

interface Migration {
  version: number;
  description: string;
  up: string;
}

const MIGRATIONS: Migration[] = [
  {
    version: 1,
    description: 'citation_key table + uniqueness index',
    up: `
CREATE TABLE citation_key (
  item_key     TEXT PRIMARY KEY,
  citation_key TEXT NOT NULL,
  origin       TEXT NOT NULL,
  updated_at   INTEGER NOT NULL
) STRICT;

CREATE UNIQUE INDEX citation_key_uniq ON citation_key(citation_key);
`,
  },
];

export interface CitationKeyRecord {
  key: string;
  origin: ZoteroCitationKeyOrigin;
}

export interface CitationKeyStoreOptions {
  /**
   * Absolute path to the directory that will contain `citations.db`. Created
   * recursively if absent. Typical value: `{userData}/scipen-studio/zotero/`.
   */
  rootDir: string;
}

export class CitationKeyStore {
  private readonly db: DatabaseSync;
  private closed = false;
  private readonly getStmt: ReturnType<DatabaseSync['prepare']>;
  private readonly upsertStmt: ReturnType<DatabaseSync['prepare']>;
  private readonly deleteConflictStmt: ReturnType<DatabaseSync['prepare']>;
  private readonly listAllStmt: ReturnType<DatabaseSync['prepare']>;

  constructor(opts: CitationKeyStoreOptions) {
    fs.mkdirSync(opts.rootDir, { recursive: true });
    const dbPath = path.join(opts.rootDir, 'citations.db');
    this.db = new DatabaseSyncCtor(dbPath);
    // Any failure between opening the DB and finishing prepared-statement
    // caching leaves an unowned handle behind. Wrap the whole bootstrap so a
    // migration failure / permission problem / bad SQL closes the file before
    // rethrowing, instead of leaking file descriptors + WAL journals.
    try {
      this.db.exec('PRAGMA journal_mode = WAL');
      this.db.exec('PRAGMA synchronous = NORMAL');
      this.db.exec('PRAGMA foreign_keys = ON');
      this.bootstrapMigrationTable();
      this.runMigrations();
      this.getStmt = this.db.prepare(
        'SELECT citation_key AS key, origin FROM citation_key WHERE item_key = ?'
      );
      this.upsertStmt = this.db.prepare(
        `INSERT INTO citation_key (item_key, citation_key, origin, updated_at)
         VALUES (?, ?, ?, ?)
         ON CONFLICT(item_key) DO UPDATE SET
           citation_key = excluded.citation_key,
           origin       = excluded.origin,
           updated_at   = excluded.updated_at`
      );
      this.deleteConflictStmt = this.db.prepare('DELETE FROM citation_key WHERE citation_key = ?');
      this.listAllStmt = this.db.prepare('SELECT citation_key AS key FROM citation_key');
    } catch (err) {
      try {
        this.db.close();
      } catch {
        // Ignore secondary close failure; the primary error is what matters.
      }
      this.closed = true;
      throw err;
    }
  }

  /**
   * Read the stored key for one Zotero item. Returns null when the item was
   * never seen (typical on first bootstrap of a fresh library).
   */
  get(itemKey: string): CitationKeyRecord | null {
    this.assertOpen();
    if (!itemKey) return null;
    const row = this.getStmt.get(itemKey) as { key?: string; origin?: string } | undefined;
    if (!row || typeof row.key !== 'string' || typeof row.origin !== 'string') return null;
    if (!isValidOrigin(row.origin)) return null;
    return { key: row.key, origin: row.origin };
  }

  /**
   * Insert or replace one entry. Throws (via sqlite unique-index enforcement)
   * if `key` collides with a *different* item's stored key — callers must
   * either check `getAllExistingKeys()` first (fresh mint path) or call
   * `updateFromBbt()` (BBT-wins path).
   */
  put(itemKey: string, key: string, origin: ZoteroCitationKeyOrigin): void {
    this.assertOpen();
    if (!itemKey || !key) {
      throw new Error('CitationKeyStore.put requires non-empty itemKey and key');
    }
    this.upsertStmt.run(itemKey, key, origin, Date.now());
  }

  /**
   * BBT-priority write: BBT-synced key always wins over prior studio_mint.
   * Runs in a transaction so we can safely (a) evict any row currently
   * holding `bbtKey` (freeing the unique index) and (b) upsert `itemKey →
   * bbtKey` in one atomic step. Throws on empty inputs so callers can't
   * silently no-op through a typo (Layer 1 in the orchestrator relies on
   * exceptions to log + fall through).
   */
  updateFromBbt(itemKey: string, bbtKey: string): void {
    this.assertOpen();
    if (!itemKey || !bbtKey) {
      throw new Error('CitationKeyStore.updateFromBbt requires non-empty itemKey and bbtKey');
    }
    this.runInTransaction(() => {
      this.deleteConflictStmt.run(bbtKey);
      this.upsertStmt.run(itemKey, bbtKey, 'bbt' satisfies ZoteroCitationKeyOrigin, Date.now());
    });
  }

  /**
   * User-driven override: force `itemKey → key` and evict any conflicting
   * holder of `key`. Same transactional shape as updateFromBbt, distinct
   * origin so the UI can highlight "user-touched" keys. Empty inputs throw
   * for the same reason (see updateFromBbt).
   */
  setUserOverride(itemKey: string, key: string): void {
    this.assertOpen();
    if (!itemKey || !key) {
      throw new Error('CitationKeyStore.setUserOverride requires non-empty itemKey and key');
    }
    this.runInTransaction(() => {
      this.deleteConflictStmt.run(key);
      this.upsertStmt.run(
        itemKey,
        key,
        'user_override' satisfies ZoteroCitationKeyOrigin,
        Date.now()
      );
    });
  }

  /**
   * Snapshot of every currently-issued key. Fed to `mintCitationKey`'s
   * collision-detection set. O(row count); fine for typical Zotero libraries
   * (thousands, not millions).
   */
  getAllExistingKeys(): Set<string> {
    this.assertOpen();
    const out = new Set<string>();
    for (const row of this.listAllStmt.all() as Array<{ key?: string }>) {
      if (typeof row.key === 'string' && row.key.length > 0) out.add(row.key);
    }
    return out;
  }

  close(): void {
    if (this.closed) return;
    this.closed = true;
    this.db.close();
  }

  // ---------- internals ----------

  private assertOpen(): void {
    if (this.closed) throw new Error('CitationKeyStore is closed');
  }

  /**
   * Run `fn` inside a BEGIN/COMMIT transaction with defensive rollback.
   * If `fn` throws we ROLLBACK; if ROLLBACK itself throws (no active tx /
   * db lock), swallow that secondary error so we surface the original
   * cause instead of the rollback failure — otherwise the actual reason
   * a citation-key write failed would be masked by a generic sqlite error.
   */
  private runInTransaction(fn: () => void): void {
    this.db.exec('BEGIN');
    try {
      fn();
      this.db.exec('COMMIT');
    } catch (err) {
      try {
        this.db.exec('ROLLBACK');
      } catch (rollbackErr) {
        logger.warn('CitationKeyStore ROLLBACK failed after write error', {
          primaryError: err instanceof Error ? err.message : String(err),
          rollbackError: rollbackErr instanceof Error ? rollbackErr.message : String(rollbackErr),
        });
      }
      throw err;
    }
  }

  private bootstrapMigrationTable(): void {
    this.db.exec(`
      CREATE TABLE IF NOT EXISTS schema_migration (
        version    INTEGER PRIMARY KEY,
        applied_at INTEGER NOT NULL,
        description TEXT NOT NULL
      ) STRICT;
    `);
  }

  private runMigrations(): void {
    const applied = (
      this.db.prepare('SELECT COALESCE(MAX(version), 0) AS v FROM schema_migration').get() as {
        v: number;
      }
    ).v;
    const pending = MIGRATIONS.filter((m) => m.version > applied).sort(
      (a, b) => a.version - b.version
    );
    if (pending.length === 0) return;
    const insertRecord = this.db.prepare(
      'INSERT INTO schema_migration (version, applied_at, description) VALUES (?, ?, ?)'
    );
    this.db.exec('BEGIN');
    try {
      for (const m of pending) {
        this.db.exec(m.up);
        insertRecord.run(m.version, Date.now(), m.description);
        logger.info('applied migration', { version: m.version, description: m.description });
      }
      this.db.exec('COMMIT');
    } catch (err) {
      this.db.exec('ROLLBACK');
      throw err;
    }
  }
}

/**
 * Enumerate every valid ZoteroCitationKeyOrigin variant. The `satisfies`
 * clause plus the `Record<...>` type guarantees the compiler flags any
 * added / removed variant in shared/types/zotero.ts — a plain string set
 * would silently drift.
 */
const VALID_ORIGIN_MAP = {
  bbt: true,
  studio_mint: true,
  user_override: true,
} as const satisfies Record<ZoteroCitationKeyOrigin, true>;

const VALID_ORIGINS: ReadonlySet<string> = new Set(Object.keys(VALID_ORIGIN_MAP));

function isValidOrigin(v: string): v is ZoteroCitationKeyOrigin {
  return VALID_ORIGINS.has(v);
}

// ---------- Singleton factory (uses app.getPath('userData') lazily) ----------

let singleton: CitationKeyStore | null = null;

/**
 * Get the process-wide CitationKeyStore singleton, rooted at
 * `{userData}/scipen-studio/zotero/`. Lazy — first call opens the DB, later
 * calls reuse it. Tests should NOT call this; construct via `new
 * CitationKeyStore({ rootDir })` with a tmp dir to keep tests hermetic.
 */
export function getCitationKeyStore(): CitationKeyStore {
  if (!singleton) {
    // Deferred require so the module loads outside Electron (unit tests, ts-node).
    const { app } = _require('electron') as typeof import('electron');
    const rootDir = path.join(app.getPath('userData'), 'scipen-studio', 'zotero');
    singleton = new CitationKeyStore({ rootDir });
    logger.info('CitationKeyStore initialized', { rootDir });
  }
  return singleton;
}
